#!/usr/bin/env python3
"""
Social Media Automation for First City Foundry
================================================

Post to Twitter/X and LinkedIn on a schedule.
Content is either hand-written or generated by ai_content.py.

Supports:
- Immediate posting to Twitter and LinkedIn
- Scheduled queue (JSON file, processed by daily_automation)
- Content calendar generation via AI
"""

import os
import json
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

logger = logging.getLogger(__name__)

ROOT_DIR = Path(__file__).parent.parent
QUEUE_FILE = ROOT_DIR / "content" / "social" / "queue.json"


# ── Twitter / X ──────────────────────────────────────────────

class TwitterPoster:
    """Post to Twitter/X via OAuth 1.0a (v2 API)."""

    def __init__(self):
        self.api_key = os.getenv("TWITTER_API_KEY", "")
        self.api_secret = os.getenv("TWITTER_API_SECRET", "")
        self.access_token = os.getenv("TWITTER_ACCESS_TOKEN", "")
        self.access_secret = os.getenv("TWITTER_ACCESS_SECRET", "")
        self.enabled = all([self.api_key, self.api_secret, self.access_token, self.access_secret])

        if not self.enabled:
            logger.info("Twitter credentials not configured — posting disabled")

    def post(self, text: str) -> Optional[Dict]:
        """Post a tweet. Returns API response dict or None."""
        if not self.enabled:
            logger.warning("Twitter not configured, skipping post")
            return None

        from requests_oauthlib import OAuth1Session

        twitter = OAuth1Session(
            self.api_key,
            client_secret=self.api_secret,
            resource_owner_key=self.access_token,
            resource_owner_secret=self.access_secret,
        )
        resp = twitter.post(
            "https://api.twitter.com/2/tweets",
            json={"text": text[:280]},
        )

        if resp.status_code == 201:
            data = resp.json()
            logger.info(f"Tweet posted: {data['data']['id']}")
            return data
        else:
            logger.error(f"Twitter error {resp.status_code}: {resp.text}")
            return None


# ── LinkedIn ─────────────────────────────────────────────────

class LinkedInPoster:
    """Post to LinkedIn organization page via REST API."""

    def __init__(self):
        self.access_token = os.getenv("LINKEDIN_ACCESS_TOKEN", "")
        self.org_id = os.getenv("LINKEDIN_ORG_ID", "")
        self.enabled = bool(self.access_token and self.org_id)

        if not self.enabled:
            logger.info("LinkedIn credentials not configured — posting disabled")

    def post(self, text: str) -> Optional[Dict]:
        """Publish a text post to an organization page."""
        if not self.enabled:
            logger.warning("LinkedIn not configured, skipping post")
            return None

        import httpx

        payload = {
            "author": f"urn:li:organization:{self.org_id}",
            "lifecycleState": "PUBLISHED",
            "specificContent": {
                "com.linkedin.ugc.ShareContent": {
                    "shareCommentary": {"text": text},
                    "shareMediaCategory": "NONE",
                }
            },
            "visibility": {"com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"},
        }

        resp = httpx.post(
            "https://api.linkedin.com/v2/ugcPosts",
            headers={
                "Authorization": f"Bearer {self.access_token}",
                "X-Restli-Protocol-Version": "2.0.0",
            },
            json=payload,
            timeout=30,
        )

        if resp.status_code == 201:
            logger.info("LinkedIn post published")
            return resp.json()
        else:
            logger.error(f"LinkedIn error {resp.status_code}: {resp.text}")
            return None


# ── Queue manager ────────────────────────────────────────────

class SocialQueue:
    """Manage a JSON queue of scheduled social posts."""

    def __init__(self):
        QUEUE_FILE.parent.mkdir(parents=True, exist_ok=True)
        self.queue: List[Dict] = self._load()

    def _load(self) -> List[Dict]:
        if QUEUE_FILE.exists():
            with open(QUEUE_FILE) as f:
                return json.load(f)
        return []

    def _save(self):
        with open(QUEUE_FILE, "w") as f:
            json.dump(self.queue, f, indent=2)

    def add(self, platform: str, text: str, scheduled_for: Optional[str] = None):
        """Add a post to the queue."""
        self.queue.append({
            "platform": platform,
            "text": text,
            "scheduled_for": scheduled_for or datetime.now().isoformat(),
            "status": "pending",
            "created": datetime.now().isoformat(),
        })
        self._save()
        logger.info(f"Queued {platform} post for {scheduled_for or 'now'}")

    def process_due(self, dry_run: bool = False) -> int:
        """Post everything whose scheduled_for is in the past. Returns count posted."""
        now = datetime.now().isoformat()
        twitter = TwitterPoster()
        linkedin = LinkedInPoster()

        posted = 0
        for item in self.queue:
            if item["status"] != "pending":
                continue
            if item["scheduled_for"] > now:
                continue

            platform = item["platform"]
            text = item["text"]

            if dry_run:
                logger.info(f"[DRY RUN] Would post to {platform}: {text[:80]}...")
                item["status"] = "dry_run"
                posted += 1
                continue

            result = None
            if platform == "twitter":
                result = twitter.post(text)
            elif platform == "linkedin":
                result = linkedin.post(text)

            item["status"] = "posted" if result else "failed"
            item["posted_at"] = datetime.now().isoformat()
            posted += 1

        self._save()
        return posted

    def pending_count(self) -> int:
        return sum(1 for item in self.queue if item["status"] == "pending")

    def summary(self) -> Dict:
        """Return status counts."""
        counts: Dict[str, int] = {}
        for item in self.queue:
            counts[item["status"]] = counts.get(item["status"], 0) + 1
        return counts


# ── Content calendar ─────────────────────────────────────────

def generate_weekly_calendar(topics: List[str] = None) -> List[Dict]:
    """Use AI to create a week's worth of social posts and queue them."""
    from ai_content import AIContentEngine

    engine = AIContentEngine()
    queue = SocialQueue()

    if not topics:
        topics = [
            "Why solo founders need structured support (not just mentorship)",
            "How the VMI Index helps founders know where they stand",
            "Portland's startup scene is quietly booming",
            "What we look for in First City Foundry partners",
            "The Foundry podcast: new episode teaser",
        ]

    base = datetime.now().replace(hour=10, minute=0, second=0, microsecond=0)
    posts = []

    for i, topic in enumerate(topics):
        scheduled = (base + timedelta(days=i)).isoformat()

        for platform in ["twitter", "linkedin"]:
            text = engine.generate_social_post(platform, topic)
            queue.add(platform, text, scheduled)
            posts.append({"day": i, "platform": platform, "topic": topic, "text": text})

    logger.info(f"Queued {len(posts)} posts for the next {len(topics)} days")
    return posts


# ── CLI entry point ──────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    parser = argparse.ArgumentParser(description="Social Media Automation — First City Foundry")
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("status", help="Show queue status")
    pp = sub.add_parser("post", help="Post immediately")
    pp.add_argument("--platform", choices=["twitter", "linkedin"], required=True)
    pp.add_argument("--text", required=True)

    qp = sub.add_parser("queue", help="Add to queue")
    qp.add_argument("--platform", choices=["twitter", "linkedin"], required=True)
    qp.add_argument("--text", required=True)
    qp.add_argument("--schedule", help="ISO datetime to post at")

    sub.add_parser("process", help="Process due posts from queue")
    sub.add_parser("calendar", help="Generate a weekly content calendar via AI")

    dp = sub.add_parser("dry-run", help="Process queue in dry-run mode")

    args = parser.parse_args()
    q = SocialQueue()

    if args.command == "status":
        print(json.dumps(q.summary(), indent=2))
        print(f"Pending: {q.pending_count()}")
    elif args.command == "post":
        if args.platform == "twitter":
            TwitterPoster().post(args.text)
        else:
            LinkedInPoster().post(args.text)
    elif args.command == "queue":
        q.add(args.platform, args.text, args.schedule)
    elif args.command == "process":
        count = q.process_due()
        print(f"Posted {count} items")
    elif args.command == "calendar":
        posts = generate_weekly_calendar()
        for p in posts:
            print(f"Day {p['day']} [{p['platform'].upper()}] {p['topic'][:50]}...")
    elif args.command == "dry-run":
        count = q.process_due(dry_run=True)
        print(f"Would post {count} items")
    else:
        parser.print_help()
