# Generated by Django 3.2.18 on 2023-04-19 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('inquiry', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('spam', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Foundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name your hunt, i.e. The Search for Ops Commander', max_length=255)),
                ('industry', models.CharField(blank=True, help_text='Market or Industry Focus', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Geographic Location of Foundry', max_length=255)),
                ('remote', models.CharField(blank=True, help_text='Remote, In-Office or Hybrid', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Describe in detail the program')),
                ('brief', models.FileField(blank=True, help_text='Document Upload', null=True, upload_to='')),
                ('url', models.CharField(blank=True, help_text='Your GitHub Profile URL', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Planned', 'Planned'), ('Started', 'Started'), ('Found', 'Found'), ('CANCELED', 'CANCELED')], default='DRAFT', help_text='How far along is the Foundry', max_length=255)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_profile', models.CharField(blank=True, max_length=255)),
                ('company_url', models.CharField(blank=True, max_length=255)),
                ('company_industry', models.CharField(blank=True, max_length=255)),
                ('elevator_pitch', models.CharField(blank=True, max_length=255)),
                ('pitch_deck', models.FileField(blank=True, help_text='Document Upload', null=True, upload_to='')),
                ('business_plan', models.FileField(blank=True, help_text='Document Upload', null=True, upload_to='')),
                ('status', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('foundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundry.foundry')),
            ],
        ),
    ]
