# Generated by Django 3.2.18 on 2023-09-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('foundry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparableCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Comparable Company',
                'verbose_name_plural': 'Comparable Companies',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StartupApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('legal_structure', models.CharField(max_length=50)),
                ('ownership_structure', models.CharField(max_length=50)),
                ('annual_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outstanding_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('founder_names', models.CharField(max_length=255)),
                ('team_members', models.TextField()),
                ('advisors_mentors', models.TextField()),
                ('target_audience', models.TextField()),
                ('competition_analysis', models.TextField()),
                ('market_demand_proof', models.TextField()),
                ('marketing_strategy', models.TextField()),
                ('development_stage', models.CharField(max_length=50)),
                ('intellectual_property', models.TextField()),
                ('customer_base', models.TextField()),
                ('customer_acquisition_strategy', models.TextField()),
                ('current_funding_sources', models.TextField()),
                ('future_funding_plans', models.TextField()),
                ('regulatory_compliance', models.TextField()),
                ('legal_issues', models.TextField()),
                ('scalability', models.TextField()),
                ('expansion_plans', models.TextField()),
                ('social_impact', models.TextField(blank=True, null=True)),
                ('revenue_model', models.TextField()),
                ('pricing_strategy', models.TextField()),
                ('competitive_advantage', models.TextField()),
                ('milestones_achievements', models.TextField()),
                ('references_recommendations', models.TextField()),
                ('alignment_with_mission', models.TextField()),
                ('support_requested', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Startup Application',
                'verbose_name_plural': 'Startup Applications',
            },
        ),
        migrations.CreateModel(
            name='SuccessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_count', models.PositiveIntegerField()),
                ('comparable_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foundry.comparablecompany')),
            ],
            options={
                'verbose_name': 'Success Data',
                'verbose_name_plural': 'Success Data',
            },
        ),
        migrations.AddField(
            model_name='comparablecompany',
            name='startups',
            field=models.ManyToManyField(related_name='comparable_companies', to='foundry.StartupApplication'),
        ),
    ]
