# Generated by Django 3.2.18 on 2023-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0002_auto_20230925_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupapplication',
            name='pitch_deck',
            field=models.FileField(blank=True, help_text='Document Upload', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='advisors_mentors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='alignment_with_mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='competition_analysis',
            field=models.TextField(help_text='List your closest Competitors'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='customer_acquisition_strategy',
            field=models.TextField(help_text='What is your plan to get them to pay for/use your product'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='customer_base',
            field=models.TextField(help_text='Have you Identified your Users or Personas'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='development_stage',
            field=models.CharField(choices=[('Idea Stage', 'Idea Stage'), ('Market Fit', 'Market Fit'), ('Proof of Concept', 'Proof of Concept'), ('MVP', 'MVP'), ('Growth Stage', 'Growth Stage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='expansion_plans',
            field=models.TextField(blank=True, help_text='How do you plan to grow and expand', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='intellectual_property',
            field=models.TextField(help_text='What IP have your registered or plan to register'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='legal_issues',
            field=models.TextField(blank=True, help_text='What if/any possible legal or regulatory issues have you identified', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='legal_structure',
            field=models.CharField(choices=[('C Corp', 'C Corp'), ('LLC', 'LLC'), ('Partnership', 'Partnership'), ('Non-Profit', 'Non-Profit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='market_demand_proof',
            field=models.TextField(help_text='Any research, surveys or signups you have summarize them here'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='marketing_strategy',
            field=models.TextField(help_text='Your marketing plans other then paid advertising'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='milestones_achievements',
            field=models.TextField(help_text='List Milestones/Acheivments so far for your Product'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='references_recommendations',
            field=models.TextField(blank=True, help_text='Customer or Investor References', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='regulatory_compliance',
            field=models.TextField(blank=True, help_text='Any Government or other compliance issues you need to address', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='revenue_model',
            field=models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('B2G', 'B2G'), ('B2B2C', 'B2B2C')], max_length=50),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='scalability',
            field=models.TextField(help_text='How well will your product scale'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='social_impact',
            field=models.TextField(blank=True, help_text='Do you have a social mission or see a positive social impact with your product', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='support_requested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='target_audience',
            field=models.TextField(help_text='Primary and Secondary Markets'),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='team_members',
            field=models.TextField(blank=True, help_text='If you have employees on payroll list them here', null=True),
        ),
    ]
