# Generated by Django 3.2.25 on 2024-03-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0002_auto_20240307_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupapplication',
            name='expansion_plans',
        ),
        migrations.RemoveField(
            model_name='startupapplication',
            name='scalability',
        ),
    ]
