# Generated by Django 4.2.11 on 2024-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0003_auto_20240308_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupapplication',
            name='competition_analysis',
            field=models.TextField(blank=True, help_text='List your closest Competitors', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='competitive_advantage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='completeness_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='customer_acquisition_strategy',
            field=models.TextField(blank=True, help_text='What is your plan to get them to pay for/use your product', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='customer_base',
            field=models.TextField(blank=True, help_text='Have you Identified your Users or Personas', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='feasibility_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='intellectual_property',
            field=models.TextField(blank=True, help_text='What IP have your registered or plan to register', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='market_demand_proof',
            field=models.TextField(blank=True, help_text='Any research, surveys or signups you have summarize them here', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='marketability_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='marketing_strategy',
            field=models.TextField(blank=True, help_text='Your marketing plans other then paid advertising', null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='originality_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='pricing_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
