# Generated by Django 4.2.11 on 2024-06-26 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foundry', '0004_alter_startupapplication_competition_analysis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationscores',
            options={'verbose_name': 'Evaluation Scores', 'verbose_name_plural': 'Evaluation Scores'},
        ),
        migrations.AddField(
            model_name='evaluationscores',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationscores',
            name='advisor_completeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationscores',
            name='advisor_feasibility_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationscores',
            name='advisor_marketability_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationscores',
            name='advisor_originality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationscores',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
