# Generated by Django 4.2.11 on 2024-06-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0005_alter_evaluationscores_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupapplication',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='pitch_deck',
            field=models.FileField(blank=True, help_text='Pitch Deck Upload', null=True, upload_to=''),
        ),
    ]
