# Generated by Django 4.2.11 on 2024-06-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0006_startupapplication_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupapplication',
            name='contact_email',
            field=models.CharField(max_length=255),
        ),
    ]
