# Generated by Django 4.2.11 on 2024-06-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0007_alter_startupapplication_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationscores',
            name='completeness_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationscores',
            name='feasibility_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationscores',
            name='marketability_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationscores',
            name='originality_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='completeness_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='feasibility_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='marketability_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupapplication',
            name='originality_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
