# Generated by Django 4.2.11 on 2024-08-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0008_alter_evaluationscores_completeness_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupapplication',
            name='ownership_structure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
