# Generated by Django 4.2.11 on 2024-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0009_alter_startupapplication_ownership_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupapplication',
            name='gemini_completeness_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='gemini_feasibility_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='gemini_marketability_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='gemini_originality_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupapplication',
            name='gemini_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
