# Generated by Django 4.2.11 on 2024-09-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundry', '0010_startupapplication_gemini_completeness_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupapplication',
            name='referral_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
